steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/hi-dev-238305/captain-hook', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/hi-dev-238305/captain-hook']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'captain-hook', '--image', 'gcr.io/hi-dev-238305/captain-hook', '--platform', 'managed', '--region', 'us-central1']
images:
- gcr.io/hi-dev-238305/captain-hook